### ISSUE TITLE
[Python] Develop function to search dictionary for 'n' consecutive empty values

### ISSUE THREAD

**Issue by rela-v** [rela-v/py-study-planner#1]
"py-study-planner" is a simple automated exam study plan maker for students which is under active development. It is written in Python and made for the command line. Right now, there is a way to create an empty "schedule" dictionary (with all hours after the current one until the midnight before the exam), but there is no function to check for "free time" (empty dictionary values) (so that future functions can utilize that information to populate the dictionary).

I think that there should be a function to check for n consecutive empty values (n being determined by the amount of time required, as determined by the length of the "task" i.e. the time attributed to any one study resource during the span of one day).

Alternatively, although it would be nice to manipulate the dictionary structure, it is completely fine to instead use lists and then append those to a pandas DataFrame.

I think this is a pretty simple task and wouldn't take long if I had to do it myself, but for any Python coders in the community who might want to take on a good first issue and contribute to an open source project, this might be a freebie that's worth looking at.

**Comment by KladeRe** [comment]
I found the function find_time() in scheduler.py which lacks an implementation. Is this issue regarding that function or do you want a whole new function?

**Comment by KladeRe** [comment]
Another question. What is the format of the dictionary. Are both start and end times directly readable from the dictionary and can we assume that the dictionary is ordered, or am I free to decide the format of the schedule dictionary?
