### ISSUE TITLE
Tests in tests/ cannot be run in Linux

### ISSUE THREAD

**Issue by KladeRe** [rela-v/py-study-planner#10]
---
name: Bug report
about: Create a report to help us improve
title: '' Tests in tests/ cannot be run in Linux #10 "
labels: ''"
assignees: ''"

---

**Describe the bug**
tests don't run in Linux when the command `coverage run -m pytest tests/` is run.

**To Reproduce**
1. Go to root directory
2. Run `coverage run -m pytest tests/`

**Expected behavior**
Tests should be run

**Comment by rela-v** [comment]
Absolutely approved. I've invited you as a collaborator as well, and feel free to submit the PR.
