### ISSUE TITLE
OOP refactoring

### ISSUE THREAD

**Issue by rela-v** [rela-v/py-study-planner#14]
---
name: Feature request
about: Suggest an idea for this project
title: 'OOP refactoring'
labels: 'enhancement'
assignees: '[@rela-v](https://github.com/rela-v)'

---

**Is your feature request related to a problem? Please describe.**
Function testing is a little awkward right now.

**Describe the solution you'd like**
The program's logic might be better served with an OOP framework for things like exams and schedules.

**Describe alternatives you've considered**
Could also alternatively go with the current use of functions and test as in https://github.com/rela-v/py-study-planner/pull/13 .

**Comment by KladeRe** [comment]
So how is it going with the OPP refactoring? If you want to I can join in and help with it. I was also wondering whether it would be smart to use a dataclass for representing exams since it would remove a lot of boilerplate code.

**Comment by rela-v** [comment]
It's definitely been busy on my end, so I haven't even touched it -- I can absolutely approve a PR and I'll go ahead and do that for the one you've linked!!
