### ISSUE TITLE
Exam ID could use some improvement

### ISSUE THREAD

**Issue by KladeRe** [rela-v/py-study-planner#17]
---
name: Bug report
about: Create a report to help us improve
title: ''Exam ID creates problems"
labels: ''question"
assignees: ''"

---

**Describe the bug**
Since exam IDs are made using a random generator, there is a considerable amount of code spent looking for duplicate ids in the add_exam function. It also doesn't help that  edit_exam assumes that all names of the exams are unique when they don't have to be.

**To Reproduce**
1. Create two exams with the same name
2. Try to edit the second exam.
3. Only the first one gets edited.

**Expected behavior**
Code should be simpler.

**Additional context**
I would recommend changing the exam database so that the names of the exams are the keys. This would remove the necessity of using exam ids and it would also force every exam name to be unique which would help with the edit_exam() function. Another possibility would be to use serial numbers. Every time a new exam is created the function reads the exam id of the last exam and increments its id by 1 and uses that value for the new exam ID. But what do you think of these solutions? I am ready to fix this but I want your input on this first before I start doing these changes.

**Comment by rela-v** [comment]
Wonderful suggestion! I'm more than happy to approve this, feel free to also keep me posted in the comments and post a PR!

**Comment by rela-v** [comment]
I'm going to go ahead and hold of on the OOP refactoring mentioned in https://github.com/rela-v/py-study-planner/issues/14 until you've made some progress on this since I wouldn't wanna step on your toes at all! I'll be writing some code in the background though, so no rush.
