### ISSUE TITLE
Program throws error when trying to list all tasks when there is no exam_data.json

### ISSUE THREAD

**Issue by KladeRe** [rela-v/py-study-planner#5]
**Describe the bug**
The program crashes when trying to list all tasks when there is no exam_data.json file

**To Reproduce**
remove exam_data.json file
start program
press 'e' and enter
press 'l' and enter

**Expected behavior**
Program should not crash

**Comment by rela-v** [comment]
Issue resolved. Future PR's will automatically close issues with the new "pull_request_template.md" found in the .github/PULL_REQUEST_TEMPLATE/ folder.
